---
- name: Reboot host
  reboot:
    reboot_timeout: 3600
    connect_timeout: 5
    post_reboot_delay: 60
  notify: 
    - Refresh facts
    - Start MST

- name: Start MST
  shell: 'mst start'

- name: Refresh facts
  setup:
