---
- set_fact:
    mellanox_ib_driver_name: "MLNX_OFED_LINUX-{{mlnx_ofed_version}}-{{ansible_facts['lsb']['id'] | lower}}{{ansible_facts['lsb']['release']}}-{{ansible_facts['machine']}}"
  changed_when: False

- set_fact:
    mellanox_ib_driver_url: "https://content.mellanox.com/ofed/MLNX_OFED-{{mlnx_ofed_version}}/{{mellanox_ib_driver_name}}.tgz"
  changed_when: False

- name: Pull Mellanox drivers
  shell: 'curl -L {{ mellanox_ib_driver_url }} | tar -xz'
  args:
    creates: '~/{{ mellanox_ib_driver_name }}/'
    chdir: '~'
    warn: no
  notify: Run mlnxofedinstall

- name: Force all handlers to run
  meta: flush_handlers
