---
- debug:
    var: hostvars[groups[group_name][0]]

- name: Clone Freeflow repo
  become: yes
  become_user: "{{ ansible_user }}"
  command: 'git clone https://github.com/emersonford/Freeflow.git'
  args:
    creates: '~/Freeflow'
    chdir: '~'
  notify:
    - Replace first IP in header
    - Replace second IP in header
    - Replace first IP in cpp
    - Replace second IP in cpp
    - Replace device idx
    - Enable verbose logging
    - Build base Docker image
    - Build ffrouter Docker image
    - Build ffclient Docker image

- name: Create start-containers.sh file
  become: yes
  become_user: "{{ ansible_user }}"
  template:
    dest: '~/Freeflow/start-containers.sh'
    mode: '744'
    src: 'start-containers.sh'
  vars:
    host_ip_addr: "{{ ansible_ens1f0.ipv4.address }}/{{ ansible_ens1f0.ipv4.netmask }}"
    freeflow_host_ip_prefix: "{{ host_ip_addr | ansible.netcommon.ipaddr('address/prefix') }}"
