---
- name: get RoCE interface name
  shell: "ip -o addr show to {{ roce_interface_subnet }} | awk '{print $2}'"
  register: roce_if_name_cmd
  changed_when: False

- set_fact: 
    roce_if_name: "{{ roce_if_name_cmd.stdout }}"
  changed_when: False

- name: Clone Freeflow repo
  become: yes
  become_user: "{{ ansible_user }}"
  command: 'git clone https://github.com/emersonford/Freeflow.git'
  args:
    creates: '~/Freeflow'
    chdir: '~'
  notify:
    - Replace first IP in header
    - Replace second IP in header
    - Replace first IP in cpp
    - Replace second IP in cpp
    - Replace device idx
  # - Enable verbose logging in server
  # - Enable verbose logging in client
    - Build base Docker image
    - Build ffrouter Docker image
    - Build ffclient Docker image

- name: Create start-containers.sh file
  become: yes
  become_user: "{{ ansible_user }}"
  template:
    dest: '~/Freeflow/start-containers.sh'
    mode: '744'
    src: 'start-containers.sh'
  vars:
    host_ip_addr: "{{ ansible_facts[roce_if_name].ipv4.address }}"
