ARG UBUNTU_VERSION={{ansible_facts['lsb']['release']}}

FROM ubuntu:${UBUNTU_VERSION}

# Rescope ARGS
ARG UBUNTU_VERSION

WORKDIR /root

RUN apt-get update && apt-get -y upgrade

# Install necessary packages.
RUN DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles apt -y install \
        iproute2 \
        iputils-ping \
        rdma-core \
        perftest

RUN apt-get clean \
        && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
