---
- name: Install sysstat
  apt:
    name: "sysstat"
    state: present

- name: Enable in sysstat file
  lineinfile:
    path: /etc/default/sysstat
    regexp: 'ENABLED="false"'
    line: 'ENABLED="true"'
  notify: Restart sysstat

