
all:
  vars:
    ansible_user: emerso0
    ansible_become: yes
  children:
    connectx5:
      hosts:
        connectx5_node1:
          ansible_host: amd270.utah.cloudlab.us
        connectx5_node2:
          ansible_host: amd251.utah.cloudlab.us
      vars:
        sriov_parent_device: mlx5_2
