all:
  vars:
    ansible_user: emerso0
    ansible_become: yes
  children:
    connectx3:
      hosts:
        connectx3_node1:
          ansible_host: apt008.apt.emulab.net
        connectx3_node2:
          ansible_host: apt002.apt.emulab.net
      vars:
        mlnx_ofed_version: '4.9-0.1.7.0'
        freeflow_device_name: 'mlx4_0'
        roce_interface_subnet: '128.110.96.0/22'
    connectx4:
      hosts:
        connectx4_node1:
          ansible_host: hp176.utah.cloudlab.us
        connectx4_node2:
          ansible_host: hp191.utah.cloudlab.us
      vars:
        mlnx_ofed_version: '4.9-4.1.7.0'
    connectx5:
      hosts:
        connectx5_node1:
          ansible_host: amd270.utah.cloudlab.us
        connectx5_node2:
          ansible_host: amd251.utah.cloudlab.us
      vars:
        mlnx_ofed_version: '5.5-1.0.3.2'
        sriov_parent_device: 'mlx5_2'
        NUM_OF_VFS: 1
        additional_mlnx_install_flags: "--ovs-dpdk"
    no_mlnx_ofed:
      hosts:
        no_mlnx_ofed_node1:
          ansible_host: amd021.utah.cloudlab.us
        no_mlnx_ofed_node2:
          ansible_host: amd022.utah.cloudlab.us
