all:
  hosts:
    connectx3_node1:
      ansible_host: ms0810.utah.cloudlab.us
    connectx3_node2:
      ansible_host: ms0833.utah.cloudlab.us
    connectx4_node1:
      ansible_host: hp139.utah.cloudlab.us
    connectx4_node2:
      ansible_host: hp136.utah.cloudlab.us
    connectx5_node1:
      ansible_host: amd007.utah.cloudlab.us
    connectx5_node2:
      ansible_host: amd009.utah.cloudlab.us
    connectx5_node3:
      ansible_host: amd009.utah.cloudlab.us
    connectx5_node4:
      ansible_host: amd008.utah.cloudlab.us
  vars:
    ansible_user: emerso0
    ansible_become: yes
  children:
    connectx3:
      hosts:
        connectx3_node1:
        connectx3_node2:
      vars:
        mellanox_ib_driver_name: 'MLNX_OFED_LINUX-4.9-3.1.5.0-ubuntu20.04-x86_64'
        mellanox_ib_driver_url: 'https://content.mellanox.com/ofed/MLNX_OFED-4.9-3.1.5.0/MLNX_OFED_LINUX-4.9-3.1.5.0-ubuntu20.04-x86_64.tgz'
    connectx4:
      hosts:
        connectx4_node1:
        connectx4_node2:
      vars:
        mellanox_ib_driver_name: 'MLNX_OFED_LINUX-5.1-0.6.6.0-ubuntu18.04-x86_64'
        mellanox_ib_driver_url: 'http://content.mellanox.com/ofed/MLNX_OFED-5.1-0.6.6.0/MLNX_OFED_LINUX-5.1-0.6.6.0-ubuntu18.04-x86_64.tgz'
    connectx5:
      hosts:
        connectx5_node1:
        connectx5_node2:
      vars:
        mellanox_ib_driver_name: 'MLNX_OFED_LINUX-5.4-3.0.3.0-ubuntu20.04-x86_64'
        mellanox_ib_driver_url: 'http://content.mellanox.com/ofed/MLNX_OFED-5.4-3.0.3.0/MLNX_OFED_LINUX-5.4-3.0.3.0-ubuntu20.04-x86_64.tgz'
    connectx5_old:
      hosts:
        connectx5_node3:
        connectx5_node4:
      vars:
        mellanox_ib_driver_name: 'MLNX_OFED_LINUX-4.9-4.0.8.0-ubuntu20.04-x86_64'
        mellanox_ib_driver_url: 'http://content.mellanox.com/ofed/MLNX_OFED-4.9-4.0.8.0/MLNX_OFED_LINUX-4.9-4.0.8.0-ubuntu20.04-x86_64.tgz'
