---
- name: configure ConnectX-4 nodes
  hosts: connectx4
  roles:
    - docker
    - mellanox
    - freeflow
  vars:
    group_name: connectx4

- name: configure ConnectX-3 nodes
  hosts: connectx3
  roles:
    - docker
    - mellanox
    - freeflow
    - connectx3
  vars:
    group_name: connectx3
