---
- name: Create disable_cpu_scaling.sh
  become: yes
  copy:
    src: "disable_cpu_scaling.sh"
    dest: "~/disable_cpu_scaling.sh"
    mode: "744"
  notify:
    - run disable_cpu_scaling.sh

- name: add disable_cpu_scaling.sh to cron reboot
  become: yes
  cron:
    name: "disable CPU scaling"
    special_time: reboot
    job: "~/disable_cpu_scaling.sh"
